/* MTI_DPI */

/*
 * Copyright 2002-2008 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DUMPREG
#define INCLUDED_DUMPREG

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"

typedef struct {
    unsigned int ph1_addr;
    unsigned int ph2_addr;
    unsigned int ph1_data;
    unsigned int ph2_data;
    int ph1_we;
    int ph2_we;
    int temp;
} regfile_dpi_type;

typedef struct {
    unsigned int psr;
    unsigned int y;
    unsigned int wim;
    int we;
} spr_dpi_type;

DPI_LINK_DECL DPI_DLLESPEC
void
dump(const regfile_dpi_type* regfile, const spr_dpi_type* spr);

#endif 
