/* MTI_DPI */

/*
 * Copyright 2002-2010 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_DISASM
#define INCLUDED_DISASM

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


typedef struct {
    int pid;
    int64_t ctime;
    int tid;
    int inst;
    int pc;
    int replay;
    int annul;
    int dma_mode;
    int uc_mode;
    int upc;
} disasm_info_type;

DPI_LINK_DECL DPI_DLLESPEC
void
init_disasm();

DPI_LINK_DECL DPI_DLLESPEC
void
sparc_disasm(
    const disasm_info_type* dis);

#endif 
