/* MTI_DPI */

/*
 * Copyright 2002-2008 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_MAC_FEDRIVER
#define INCLUDED_MAC_FEDRIVER

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


typedef struct {
    int rxdv;
    int rx_data;
} rx_response_type;

typedef struct {
    int tx_en;
    int tx_data;
} tx_request_type;

DPI_LINK_DECL DPI_DLLESPEC
void
init_driver();

DPI_LINK_DECL DPI_DLLESPEC
void
transfer_rx(
    rx_response_type* req);

DPI_LINK_DECL DPI_DLLESPEC
void
transfer_tx(
    const tx_request_type* req);

#endif 
