/* MTI_DPI */

/*
 * Copyright 2002-2010 Mentor Graphics Corporation.
 *
 * Note:
 *   This file is automatically generated.
 *   Please do not edit this file - you will lose your edits.
 *
 * Settings when this file was generated:
 *   PLATFORM = 'linux_x86_64'
 */
#ifndef INCLUDED_SIM_TOP
#define INCLUDED_SIM_TOP

#ifdef __cplusplus
#define DPI_LINK_DECL  extern "C" 
#else
#define DPI_LINK_DECL 
#endif

#include "svdpi.h"


DPI_LINK_DECL DPI_DLLESPEC
void
fromhost_getbyte(
    svBit* valid,
    svBitVecVal* bits);

DPI_LINK_DECL DPI_DLLESPEC
void
htif_init(
    const char* thost,
    const char* fhost);

DPI_LINK_DECL DPI_DLLESPEC
void
tohost_putbyte(
    const svBitVecVal* bits);

#endif 
